import "cam.gr"

func randf() (float) {
    return rand(-1f, 1f);
}

event app() {
    setupControls();
    setupCamera();
    yield;
    //testUI();
    runtime();
}

var boundingBox = @vec2f(800f, 600f);

task runtime() {
    spawnCircles();

    var circle = @Circle(100, @color(0f, 0.6f, 1f));
    circle:position(@vec2f(400f, 300f));
    circle:gravity();

    var rect = @Rect(10, 10, @color(1f, 0f, 0f));
    rect:position(@vec2f(400f, 300f));

    /*var rect2 = @Rect(32, 48, @color(0f, 0f, 1f));
    rect2:position(@vec2f(200f, 150f));

    var remilia = @Sprite("remilia");
    remilia:position(@vec2f(200f, 150f));

    var remilia2 = @Sprite("remilia");
    remilia2:position(@vec2f(600f, 450f));

    task() {
        var angle = 0f;
        loop yield {
            remilia:rotation(angle);
            rect2:rotation(angle);
            angle -= rad(1f);
        }
    }();*/

    //ringTest();

    //var skybox = @Skybox("night"); // @TODO fix
    //var globalLight = @DirectionalLight(@vec3f(0f, -10f, 0f), .2f, .01f);
    //var pointLight1 = @PointLight(@vec3f(-1f, 0.5f, 0f), @color(1f, 0f, 0f), 0f, 0.3f);
    //var pointLight2 = @PointLight(@vec3f(1f, 0.5f, 0f), @color(0f, 1f, 0f), 0f, 0.3f);
    //var spotLight = @SpotLight(@vec3f(0f, 5f, 0f), @vec3f(0f, -1f, 0f), @color(1f, 1f, 1f), 20f, 0.5f, 0.3f);

    //var quad = @Quad();

    //var cube = @Model("cube");

    /*var jupiter = @Model("jupiter");
    jupiter:position(@vec3f(0f, 0f, -2f));
    jupiter:scale(@vec3f(.05f, .05f, .05f));

    var reimu = @Model("reimu");
    reimu:position(@vec3f(0f, -1f, 0f));
    reimu:scale(@vec3f(0.1f, 0.1f, 0.1f));
    reimu:addTexture("reimu_body");

    var reimuHair = @Model("reimu_hair");
    reimuHair:addTexture("reimu_hair");
    reimu:addChild(reimuHair);*/

    /*var skin = @Model("skin");
    skin:position(@vec3f(0f, -1f, 0f));*/

    /*var rig = @Model("riggedsimple");
    rig:rotation(@vec3f(0f, 90f, 0f));
    rig:scale(@vec3f(0.1f, 0.1f, 0.1f));

    loop yield {
        rig:updateDisplayBoneId();
    }*/
}

func spawnCircles() {
    var positions = list<vec2f, 100>;

    /*loop(i, nbParticles) {
        positions[i] = ;
    }*/
}

func sign(x: float) (float) {
    if (x == 0) {
        return 0f;
    } else if (x > 0) {
        return 1f;
    }

    return -1f;
}

func bounce(circle: Circle, velocity: vec2f) {
    var circlePos = circle:localPosition2D;
    var bottom = boundingBox.y - circle.size / 2;
    var dredge = 0.8f;

    if (circlePos.y > bottom) {
        velocity.y *= -1 * dredge;
        circle:position(@vec2f(circlePos.x, bottom));
    }
}

task gravity(circle: Circle) {
    var deltaTime = 0.016f;
    var velocity = @vec2f(0f, 0f);

    loop yield {
        velocity += @vec2f(0f, 1f) * 9.8f * deltaTime;
        circle:position(circle:localPosition2D + velocity);
        bounce(circle, velocity);
    }
}

task ringTest() {
    loop {
        var angle = 0f;
        while (angle < 360f) {
            var bullet = @Bullet("remilia", @vec2f(400f, 300f), 2f, angle);
            angle += 15f;
        }

        sleep(0.5.seconds);
    }
}

func updateDisplayBoneId(model: Model) {
    var modelBoneId = model:displayBoneId;
    var modelNbBones = model:nbBones;

    if (isActionActivated("next_bone")) {
        if (modelBoneId == modelNbBones - 1) {
            modelBoneId = -1;
        } else {
            modelBoneId = (modelBoneId + 1) % modelNbBones;
        }
    } else if (isActionActivated("previous_bone") && modelBoneId >= -1) {
        if (modelBoneId == 0) {
            modelBoneId = -1;
        } else if (modelBoneId == -1) {
            modelBoneId = modelNbBones - 1;
        } else {
            modelBoneId = (modelBoneId - 1) % modelNbBones;
        }
    }

    model:displayBoneId(modelBoneId);
}

task testUI() {
    var label = @Label("Hello World !");
    label:position(@vec2f(200f, 200f));
    label.align(AlignX.right, AlignY.top);
    appendUI(label);

    /*var state = @UIState("hidden");
    state.ticks = 15;
    state.spline = Spline.sineInOut;
    state.alpha = 0f;
    state.offsetX = -100f;
    //state.angle = rad(45f);
    label.addState(state);

    sleep(2.seconds);
    label.runState("hidden");*/
}