export func setupControls() {
    // 3D camera
    addAction("move_left_3d");
    addAction("move_right_3d");
    addAction("move_down_3d");
    addAction("move_up_3d");
    addAction("move_back_3d");
    addAction("move_forward_3d");
    addAction("turn_up");
    addAction("turn_down");
    addAction("turn_left");
    addAction("turn_right");

    // 2D camera
    addAction("move_left_2d");
    addAction("move_right_2d");
    addAction("move_down_2d");
    addAction("move_up_2d");
    addAction("roll_left_2d");
    addAction("roll_right_2d");
    addAction("zoom_in_2d");
    addAction("zoom_out_2d");

    // Exit
    addAction("exit");

    // Bones debug
    addAction("nextBone");
    addAction("previousBone");
    
    // 3D camera
    addActionEvent("move_left_3d", @InputEvent.controllerAxis(ControllerAxis.leftX, -1f));
    addActionEvent("move_left_3d", @InputEvent.controllerButton(ControllerButton.left, KeyState.pressed));
    addActionEvent("move_left_3d", @InputEvent.keyButton(KeyButton.left, KeyState.pressed));
    addActionEvent("move_left_3d", @InputEvent.keyButton(KeyButton.a, KeyState.pressed));

    addActionEvent("move_right_3d", @InputEvent.controllerAxis(ControllerAxis.leftX, 1f));
    addActionEvent("move_right_3d", @InputEvent.controllerButton(ControllerButton.right, KeyState.pressed));
    addActionEvent("move_right_3d", @InputEvent.keyButton(KeyButton.right, KeyState.pressed));
    addActionEvent("move_right_3d", @InputEvent.keyButton(KeyButton.d, KeyState.pressed));

    addActionEvent("move_down_3d", @InputEvent.controllerAxis(ControllerAxis.leftTrigger, 1f));
    addActionEvent("move_down_3d", @InputEvent.keyButton(KeyButton.leftShift, KeyState.pressed));

    addActionEvent("move_up_3d", @InputEvent.controllerAxis(ControllerAxis.rightTrigger, 1f));
    addActionEvent("move_up_3d", @InputEvent.keyButton(KeyButton.space, KeyState.pressed));

    addActionEvent("move_back_3d", @InputEvent.controllerAxis(ControllerAxis.leftY, 1f));
    addActionEvent("move_back_3d", @InputEvent.controllerButton(ControllerButton.down, KeyState.pressed));
    addActionEvent("move_back_3d", @InputEvent.keyButton(KeyButton.down, KeyState.pressed));
    addActionEvent("move_back_3d", @InputEvent.keyButton(KeyButton.s, KeyState.pressed));

    addActionEvent("move_forward_3d", @InputEvent.controllerAxis(ControllerAxis.leftY, -1f));
    addActionEvent("move_forward_3d", @InputEvent.controllerButton(ControllerButton.up, KeyState.pressed));
    addActionEvent("move_forward_3d", @InputEvent.keyButton(KeyButton.up, KeyState.pressed));
    addActionEvent("move_forward_3d", @InputEvent.keyButton(KeyButton.w, KeyState.pressed));

    addActionEvent("turn_up_3d", @InputEvent.controllerAxis(ControllerAxis.rightY, 1f));
    addActionEvent("turn_down_3d", @InputEvent.controllerAxis(ControllerAxis.rightY, -1f));
    addActionEvent("turn_left_3d", @InputEvent.controllerAxis(ControllerAxis.rightX, -1f));
    addActionEvent("turn_right_3d", @InputEvent.controllerAxis(ControllerAxis.rightX, 1f));

    // 2D camera controls (missing movement controller inputs)
    addActionEvent("move_left_2d", @InputEvent.keyButton(KeyButton.a, KeyState.pressed));
    addActionEvent("move_right_2d", @InputEvent.keyButton(KeyButton.d, KeyState.pressed));
    addActionEvent("move_down_2d", @InputEvent.keyButton(KeyButton.s, KeyState.pressed));
    addActionEvent("move_up_2d", @InputEvent.keyButton(KeyButton.w, KeyState.pressed));

    addActionEvent("roll_left_2d", @InputEvent.controllerButton(ControllerButton.leftShoulder, KeyState.pressed));
    addActionEvent("roll_left_2d", @InputEvent.keyButton(KeyButton.q, KeyState.pressed));

    addActionEvent("roll_right_2d", @InputEvent.controllerButton(ControllerButton.rightShoulder, KeyState.pressed));
    addActionEvent("roll_right_2d", @InputEvent.keyButton(KeyButton.e, KeyState.pressed));

    addActionEvent("zoom_in_2d", @InputEvent.keyButton(KeyButton.numPlus, KeyState.pressed));
    addActionEvent("zoom_in_2d", @InputEvent.mouseWheel(0, -1));

    addActionEvent("zoom_out_2d", @InputEvent.keyButton(KeyButton.numMinus, KeyState.pressed));
    addActionEvent("zoom_out_2d", @InputEvent.mouseWheel(0, 1));

    // Exit
    addActionEvent("exit", @InputEvent.controllerButton(ControllerButton.start, KeyState.pressed));
    addActionEvent("exit", @InputEvent.keyButton(KeyButton.escape, KeyState.pressed));

    // Bones debug
    addActionEvent("previous_bone", @InputEvent.keyButton(KeyButton.f1, KeyState.down));
    addActionEvent("next_bone", @InputEvent.keyButton(KeyButton.f2, KeyState.down));
}

export var mouseX : int;
export var mouseY : int;

event input(input: InputEvent) {
    switch(input.type)
    case(InputEventType.mouseMotion) {
        var input = input.mouseMotion?;
        mouseX = input.relativeX;
        mouseY = input.relativeY;
    }

    if (isActionActivated("exit")) {
        exit;
    }
}